server:
    port: 8761
eureka:
    client:
        register-with-eureka: false
        fetch-registry: false
        serviceUrl:
            defaultZone: http://eureka-server:8761/eureka
    instance:
        hostname: eureka-server
        non-secured-port-enabled: true
        secured-port-enabled: false
        prefer-ip-address: true


